name: Docker Image CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Install Ollama
        run: |
          curl -sSL https://ollama.com/download | bash
          # Add Ollama to the PATH (optional if it's installed globally)
          export PATH=$PATH:/path/to/ollama

      - name: Run Ollama model (Optional for testing)
        run: ollama run mistral

      - name: Build Docker image
        run: docker build . --file Dockerfile --tag self_hosted_ai:$(date +%s)

      - name: Push Docker image to DockerHub (optional)
        run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker push self_hosted_ai:$(date +%s)
